# [list]
[lorem.list]
value = "lorem\t\tlorem ipsum dolor sit amet"
separator = " "
script =  """
from q3 import *;

value = normalize_spaces(value)
value = uniq(value)
value = quote(value)
value = join_or(value)
"""

# [generator]
[e.generator]
script = """
value = "lorem ipsum from generator"
"""

[q2.query]
value = " title:(#{query}) #{e}"

[query.query]
value = "title:(#{lorem}) OR abstract:(#{lorem}) #{e}"


# [query.q1]
# value = "lorem ipsum"
#
#
# [query.q2]
# value = "lorem ipsum #{q1}"
