
[lorem.list]
value = "lorem\t\tlorem ipsum dolor sit amet"
separator = " "
script =  """
from q3 import *;

value = normalize_spaces(value)
value = uniq(value)
value = quote(value)
value = join_or(value)
"""

[e.generator]
script = """
value = "lorem ipsum from generator"
"""

[query.query]
value = "title:(#{lorem}) OR abstract:(#{lorem}) #{e}"

[q2.query]
value = "title:(#{query}) #{e}"

[1.query]
value = "title:(#{lorem}) OR abstract:(#{lorem}) #{e} e"

[4.query]
value = "title:(#{lorem}) OR bstract:(#{lorem}) #{e}"


[2.query]
value = "title:(#{lorem}) OR abstract:(#{lorem}) #{e}"

[3.query]
value = "title:(#{lorem}) OR abstract:(#{lorem}) #{e}"

